[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/HURU-School/HURUAI/blob/main/Lesson%202/Numpy%20Refresher.ipynb)

# Numpy

## A little About Arrays in Python.

Arrays, sometimes called lists, organize data sequentially in memory. They are the simplest and most widely used data structure. Arrays are the best at storing data and looping over the data. 
![Arrays](../images/Lesson_2/arrays.PNG)  
Python has an array module built in but we almost always use numpy, a scientific library for python, because numpy is much more faster than the native python array module.  
**NOTE:** Python, like most programming languages is **Zero-indexed**, meaning that when counting indices in python, we alwats start at Zero and not at One.

### Creating Arrays

In [4]:
# Import the numpy library
import numpy as np

In [5]:
# Set a seed. This just makes sure that the random function is a little bit more predictable and reproducible.
np.random.seed(42)

# Create a numpy array
x = np.random.randint(10, size=6) # Creates a one-dimensional array
y = np.random.randint(10, size=(3, 4)) # Creates a two-dimensional array
z = np.random.randint(10, size=(3, 4, 5)) # Creates a three-dimensional array

### Array Attributes
The attributes of an array include:
  * ndim - the number of dimensions
  * shape - the size of each dimension
  * size - the total size of the array
  * dtype - the data type of the array
  * itemsize - the size of each element in the array(in bytes).
  * nbytes - the total size of the array(in bytes).

In [9]:
print("Array z's number of dimensions: ", z.ndim)
print("Array z's shape: ", z.shape)
print("Array z's size: ", z.size)
print("Array z's type: ", z.dtype)
print("Array z's itemsize: ", z.itemsize)
print("Array z's nbytes: ", z.nbytes)

Array z's number of dimensions:  3
Array z's shape:  (3, 4, 5)
Array z's size:  60
Array z's type:  int32
Array z's itemsize:  4
Array z's nbytes:  240


### Indexing in Arrays
This is a method to access elements in an array. It is done by specifying the index of the item desired in square brackets

In [10]:
x

array([6, 3, 7, 4, 6, 9])

In [11]:
x[2]

7

In [12]:
x[-1]

9

In multi dimensional arrays items are accessed using a comma separated tuple of indices


In [13]:
y

array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

In [14]:
y[0, 0]

2

In [18]:
y[2,-1]

7

### Iterating through a numpy array

#### Using the range fuction

In [20]:
x

array([6, 3, 7, 4, 6, 9])

In [23]:
for i in range(len(x)):
    print(x[i])

6
3
7
4
6
9


#### Using a for loop only

In [25]:
x

array([6, 3, 7, 4, 6, 9])

In [26]:
for item in x:
    print(item)

6
3
7
4
6
9


#### Using the enumerate function
The enumerate function adds a counter to the array thus relieving the overhead of keeping a count of the elements while the iteration operation in running.

In [30]:
x

array([6, 3, 7, 4, 6, 9])

In [31]:
for index, value in enumerate(x):
    print(index, ':', value)

0 : 6
1 : 3
2 : 7
3 : 4
4 : 6
5 : 9


### Array Manipulation

#### Reshaping an Array

In [36]:
# Create an array with 16 elements
m = np.arange(1, 17)
print(m)
print('The shape of array m is ', m.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
The shape of array m is  (16,)


In [37]:
m2 = m.reshape(4, 4)
print(m2)
print('The shape of array m2 is ', m2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
The shape of array m2 is  (4, 4)


#### Adding an array together
The same procedure applies for subtraction as well

In [38]:
n = m + m
print(n)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32]


In [39]:
# This throws a shape error because array m and m2 are not of the same shape
m + m2

ValueError: operands could not be broadcast together with shapes (16,) (4,4) 

#### Dot Product

In [41]:
p = np.array([6, 5])
q = np.array([7, 3])
print(p)
print(q)

[6 5]
[7 3]


In [43]:
#  the code below manually calculates dot product for p and q
dot_product = 0
for itema, itemb in zip(p, q):
    dot_product += itema * itemb
print(dot_product)

57


In [42]:
print(p.dot(q))

57


#### Matrix Multiplication

In order to multiply two matrices together, the inner dimensions of the matrices must match. Meaning, the number of columns  of the left matrix should match the number of rows on the right matrix.

In [47]:
e = np.array(([4, 5, 6], [7, 8, 9]))
f = np.array(([1, 2], [3, 4], [5, 6]))
print(e)
print ("########################")
print(f)

[[4 5 6]
 [7 8 9]]
########################
[[1 2]
 [3 4]
 [5 6]]


In [48]:
e.dot(f)

array([[ 49,  64],
       [ 76, 100]])

In [50]:
# As of python 3.5 the '@' symbol also does matrix multiplication
e @ f

array([[ 49,  64],
       [ 76, 100]])

#### Matrix Transpose

In [51]:
x = np.arange(4).reshape((2, 2))
x

array([[0, 1],
       [2, 3]])

In [52]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [55]:
y = np.ones((2, 3, 4, 5))
print(y)
print('#################')
print('The shape of matrix y is ', y.shape)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
#################
The shape of matrix y is  (2, 3, 4, 5)


In [56]:
z = np.transpose(y)
print(z)
print('##################')
print('The shape of matrix z is ', z.shape)

[[[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]]
##################
The shape of matrix z is  (5, 4, 3, 2)
